FinFlow/FinFlow/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')), # user 앱의 urls.py를 포함시킵니다.
    path('', include('finflow_control.urls')), # finflow_control 앱의 urls.py를 포함시킵니다.  
    # path('user/', include('user.urls')), 
]

FinFlow/user/urls.py
from django.urls import path, include
from .views import Logout_View
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.LoginView.as_view(), name='login'),
    path('logout/', Logout_View, name='logout'),
        
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('api/v1/id-validation', views.IdValidation.as_view(), name='id_validation'), 
    path('api/v1/hp-validation', views.HPValidation.as_view(), name='hp_validation'), 
    path('api/v1/auth-message', views.AuthView.as_view(), name='auth_message'), 
]

FinFlow/user/models.py
import os, hmac, json, time, base64, random, datetime, hashlib, requests

from .choices import *
from model_utils.models import TimeStampedModel

from django.utils import timezone
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class UserManager(BaseUserManager):
    def create_user(self, user_id, password, hp, auth, user_email, **extra_fields):
        if not user_id:
            raise ValueError('사용자 ID는 필수입니다.')
        user = self.model(
            user_id = user_id,
            hp = hp,
            auth = auth,
            user_email = user_email,            
            **extra_fields
        )
        user.set_password(password)        
        user.save(using=self._db)
        return user

    def create_superuser(self, user_id, password=None, hp=None, auth=None, user_email=None, **extra_fields):
        user = self.create_user(user_id, password, hp, auth, user_email)
        user.is_superuser = True
        user.is_admin = True
        user.is_staff = True
        user.level = 0
        user.save(using=self._db)
        return user

class User(AbstractBaseUser, PermissionsMixin):
    '''
    회원 정보 테이블, 테이블명 USER_TB
    user_id : 유저 아이디
    password : 비밀번호
    hp : 휴대폰번호
    user_email : 사용자 이메일
    
    level : 사용자 권한 등급, 개발자 0, 관리자 1, 유저는 default 2
    auth : 인증번호 6자리
    date_joined : 가입일, auto_now_add 사용
    
    card_user_id : 여신협회 가입 id
    card_user_pw : 여신협회 가입 pw
    
    bank_user_id : 은행 간편조회 가입 id
    bank_user_pw : 은행 간편조회 가입 pw
    
    agree_UserInfo : 개인정보이용동의
    agree_Marketing : 마케팅 이용동의
    '''
    objects = UserManager()

    user_id = models.CharField(max_length=17, verbose_name="아이디", unique=True)
    password = models.CharField(max_length=255, verbose_name="비밀번호")
    hp = models.CharField(max_length=11, verbose_name="휴대폰번호", null=True, unique=True)
    auth = models.CharField(max_length=6, verbose_name="인증번호", null=True)
    user_email=models.CharField(max_length=255,verbose_name="이메일",null=True, unique=True)

    level = models.CharField(choices=LEVEL_CHOICES, max_length=18, verbose_name="등급", default=2)    
    date_joined = models.DateTimeField(auto_now_add=True, verbose_name='가입일', null=True, blank=True)

    card_user_id = models.CharField(max_length=20, verbose_name="카드아이디", default="", blank=True)
    card_user_pw = models.CharField(max_length=255, verbose_name="카드비밀번호", default="", blank=True)
    
    bank_user_id = models.CharField(max_length=20, verbose_name="뱅크아이디", default="", blank=True)
    bank_user_pw = models.CharField(max_length=255, verbose_name="뱅크비밀번호", default="", blank=True)
    bank_kind = models.CharField(max_length=5, verbose_name="은행명", default="", blank=True)
    bank_number = models.CharField(max_length=20, verbose_name="통장번호", default="", blank=True)
    bank_pw = models.CharField(max_length=20, verbose_name="통장비밀번호", default="", blank=True)
    
    user_biznum = models.CharField(max_length=10, verbose_name="사업자번호", default="", blank=True)
    user_ComName = models.CharField(max_length=100, verbose_name="사업자명", default="", blank=True)
    user_address = models.CharField(max_length=200, verbose_name="사업자주소", default="", blank=True)
    
    agree_UserInfo = models.BooleanField(verbose_name="개인정보이용동의",default=False) #개인 정보 동의
    agree_Marketing = models.BooleanField(verbose_name="마케팅동의",default=False) #마케팅 정보 동의

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'user_id'
    REQUIRED_FIELDS = ['hp']       

    def __str__(self):
        return self.user_id

    class Meta:
        db_table = "FinFlow_User_TB"
        verbose_name = "모든 사용자"
        verbose_name_plural = "모든 사용자"
        managed = True

class AuthSMS(TimeStampedModel):
    '''
    회원가입 문자 인증을 위한 model, 테이블명 AUTH_TB
    네이버 sens 서비스를 통해 입력한 휴대폰 번호로 인증 번호를 보냅니다.
    인증 코드는 6자리 숫자입니다.
    '''
    hp = models.CharField(max_length=11, verbose_name='휴대폰번호', primary_key=True)
    auth = models.IntegerField(verbose_name='인증번호')

    class Meta:
        db_table = 'AUTH_TB'

    def save(self, *args, **kwargs):
        self.auth = random.randint(100000, 1000000) # 난수로 6자리 문자 인증 번호 생성
        super().save(*args, **kwargs)
        self.send_sms() # 문자 전송용 함수

    def send_sms(self):

        BASE_DIR = getattr(settings, 'BASE_DIR', None)
        file_path = "naver_cloud_sens.json" # 네이버 sens api key 파일

        with open(os.path.join(BASE_DIR,file_path), encoding='utf-8') as f:
            nc_sens_key = json.load(f)

        ##### 네이버 sens 서비스 이용 위한 json request 형식 #####
        timestamp = str(int(time.time() * 1000))

        url = "https://sens.apigw.ntruss.com"
        uri = "/sms/v2/services/ncp:sms:kr:306737371424:quickself/messages"
        apiUrl = url + uri

        access_key = nc_sens_key['NAVER_SENS_ACCESS_KEY']
        secret_key = bytes(nc_sens_key['NAVER_SENS_SECRET_KEY'], 'UTF-8')
        message = bytes("POST" + " " + uri + "\n" + timestamp + "\n" + access_key, 'UTF-8')
        signingKey = base64.b64encode(hmac.new(secret_key, message, digestmod=hashlib.sha256).digest())
        

        body = {
            "type" : "SMS",
            "contentType" : "COMM",
            "from" : "01052802707",
            "subject" : "정산유",
            "content" : "[정산유] 인증 번호 [{}]를 입력해주세요.".format(self.auth),
            "messages" : [{"to" : self.hp}]
        }
        body2 = json.dumps(body)
        headers = {
            "Content-Type": "application/json; charset=utf-8",
            "x-ncp-apigw-timestamp": timestamp,
            "x-ncp-iam-access-key": access_key,
            "x-ncp-apigw-signature-v2": signingKey
        }

        requests.post(apiUrl, headers=headers, data=body2)


    @classmethod
    def check_timer(cls, p_num, c_num)->bool:
        '''
        문자인증 제한시간을 위한 타이머 설정 함수
        '''
        time_limit = timezone.now() - datetime.timedelta(minutes=5) # minutes 변수를 통해 문자인증 제한시간 설정
        result = cls.objects.filter(
            hp=p_num,
            auth=c_num,
            modified__gte=time_limit
        )

        if result:
            return True
        return False

FinFlow/user/forms.py
from .models import User

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import check_password

class UserRegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)

        self.fields['user_id'].label = '아이디'
        self.fields['user_id'].widget.attrs.update({     
            'class': 'form-control',
            'autofocus': False
        })

        self.fields['password1'].label = '비밀번호'
        self.fields['password1'].widget.attrs.update({
            'class': 'form-control',
        })
        
        self.fields['user_biznum'].label = '사업자번호'
        self.fields['user_biznum'].widget.attrs.update({     
            'class': 'form-control',
            'autofocus': False
        })

        self.fields['hp'].label = '휴대폰번호'
        self.fields['hp'].widget.attrs.update({
            'class': 'form-control',
        })

        self.fields['auth'].label = '인증번호'
        self.fields['auth'].widget.attrs.update({
            'class': 'form-control',
        })

    class Meta:
        model = User
        fields = ['user_id', 'password1', 'password2', 'user_biznum', 'hp', 'auth',]

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.level = '2'
        user.save()

        return user

class LoginForm(forms.Form):
    user_id = forms.CharField(
        widget=forms.TextInput(
        attrs={'class': 'form-control',}), 
        max_length=16,
        label='아이디'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
        attrs={'class': 'form-control',}),
        label='비밀번호'
    )
    
    def clean(self):
        cleaned_data = super().clean()
        user_id = cleaned_data.get('user_id')
        password = cleaned_data.get('password')

        if user_id and password:
            try:
               user = User.objects.get(user_id=user_id)
            except User.DoesNotExist:
                self.add_error('user_id', '아이디가 존재하지 않습니다.')
                return
            
            if not check_password(password, user.password):
                self.add_error('password', '비밀번호가 틀렸습니다.')

FinFlow/user/views.py
from .forms import UserRegisterForm, LoginForm
from .models import User, AuthSMS
from .modules import check_auth, register_errors

from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.http import JsonResponse, HttpRequest, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, FormView

from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from user.decorators import *



### 소셜 로그인 사용 위한 url 변수 설정 ###
BASE_URL = '/'
KAKAO_CALLBACK_URI = BASE_URL + 'kakao/callback/'
NAVER_CALLBACK_URI = BASE_URL + 'naver/callback/'

# LogOut View 처리
def Logout_View(request:HttpRequest):
    logout(request)
    return redirect(BASE_URL)

# @method_decorator(logout_message_required, name='dispatch')
class LoginView(FormView):
    '''
    메인 페이지 view
    로그인 위한 form request 
    '''
    template_name = 'user/index.html'
    form_class = LoginForm
    # success_url = '/enroll'


    def form_valid(self, form):
        user_id = form.cleaned_data.get("user_id")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=user_id, password=password)

        if user is not None:            
            self.request.session['user_id'] = user_id
            login(self.request, user)
            
            if user.card_user_id and user.bank_user_id:
                return HttpResponseRedirect('/finflow_control')
            else: 
                return HttpResponseRedirect('/finflow_info')
                

        return super().form_valid(form)

    def form_invalid(self, form: LoginForm):
        messages.error(self.request, '아이디 또는 비밀번호를 확인해주세요.')
        return super().form_invalid(form)


@method_decorator(logout_message_required, name='dispatch')
class UserRegisterView(CreateView):
    '''
    회원가입 페이지 view
    register_errors 함수를 통해 에러메세지 전달
    check_auth 함수를 통해 휴대폰번호, 인증번호 매칭
    에러메세지 없을시 form 저장하고 메인페이지로 redirect
    '''
    model = User
    template_name = 'user/register.html'
    form_class = UserRegisterForm

    def form_valid(self, form):
        user_hp = form.cleaned_data['hp']
        user_auth = form.cleaned_data['auth']

        if check_auth(user_hp, user_auth) == True:
            errors = register_errors(form)

            if errors == {}:
                self.object = form.save()
                return redirect('/')
            else:
                return self.render_to_response(self.get_context_data(form=form, errors=errors))

        else:
            errors = register_errors(form)
            return self.render_to_response(self.get_context_data(form=form, errors=errors))
    
    def form_invalid(self, form):
        errors = register_errors(form)
        return self.render_to_response(self.get_context_data(form=form, errors=errors))



# For API views
class AuthView(APIView):
    '''
    받은 request data로 휴대폰번호를 통해 AuthSMS에 update_or_create
    인증번호 난수 생성및 저장은 모델 안에 존재.
    '''
    def post(self, request):
        try:
            p_num = request.data['hp']
        except KeyError:
            return Response({'message': 'Bad Request'}, status=status.HTTP_400_BAD_REQUEST)
        else:
            AuthSMS.objects.update_or_create(hp=p_num)
            return Response({'message': 'OK'})

class IdValidation(APIView):
    '''
    중복 아이디가 있는지 검증하는 API
    jquery blur로 AJAX통해 제출.
    '''
    def post(self, request):
        try:
            user_id = request.data['user_id']
            try:
                user = User.objects.get(user_id=user_id)
            except Exception as e:
                user = None
            
            context = {
                'data' : "not exist" if user is None else "exist"
            }

        except KeyError:
            return Response({'message': 'Bad Request'}, status=status.HTTP_400_BAD_REQUEST)
        else:
            return JsonResponse(context)

class HPValidation(APIView):
    '''
    중복 휴대폰 번호가 있는지 검증하는 API
    jquery blur로 AJAX통해 제출.
    '''
    def post(self, request):
        try:
            hp = request.data['hp']
            try:
                user = User.objects.get(hp=hp)
            except Exception as e:
                user = None
            
            context = {
                'data' : "not exist" if user is None else "exist"
            }

        except KeyError:
            return Response({'message': 'Bad Request'}, status=status.HTTP_400_BAD_REQUEST)
        else:
            return JsonResponse(context)

FinFlow/templates/user/index.html
{% extends 'base.html' %}
{% block content %}

{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/user/index.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
</head>

<body class="text-center">

{% if user.is_authenticated %}
<script type="text/javascript">
    location.href="/logout";
</script>

{% else %}

    <main class="form-signin">
        <form method="post" action=".">
          {% csrf_token %}

          <img class="mb-4" src="{% static 'image/pample_logo_symbol.png' %}" alt="" width="72" height="72">
          <h1 class="h3 mb-3 fw-normal">정 산 유</h1>
        
          <div class="form-floating">
              <input
                  id="floatingInput"
                  class="form-control"
                  type="id"
                  placeholder="아이디"            
                  name="user_id"
                  maxlength='17'/>

            <label for="floatingInput">
                ID
            </label>

          </div>

          <p class="mt-1 text-muted"></p>

          <div class="form-floating">
              <input
                  id="floatingPassword"
                  class="form-control"
                  type="password"
                  placeholder="Password"            
                  name="password"
                  maxlength='17'/>

            <label for="floatingPassword">
                Password
            </label>

          </div>
        
          <!-- <div class="checkbox mb-3">
            <label>
              <input type="checkbox" value="remember-me"> Remember me
            </label>
          </div> -->
          <p class="mt-2 text-muted"></p>

          <button
                class="w-100 btn btn-lg btn-primary btn-color"
                type="submit">
              로그인
          </button> 

          <p class="mt-3 text-muted"></p>     

          <button
                class="w-100 btn btn-lg btn-primary btn-color"
                onclick="location.href = '/register'; return false;">
                회원가입
          </button>

          <p class="mt-2 text-muted"></p>  

          {% load socialaccount %}
          <!--{% comment %} <button
              class="btn"
              style="text-align:left; background-image: url({% static 'image/naver.png' %}); background-size: cover;
              width: 135px; height: 37px; float:left;  border:none;"
              onclick="location.href = ''; return false;">
          </button>
          <button
              class="btn"
              style="text-align:left; background-image: url({% static 'image/kako.png' %}); background-size: cover;
              width: 135px; height: 37px; float:right; border:none;"
              onclick="location.href = '{% provider_login_url 'naver' method='oauth2' %}'; return false;">
          </button> {% endcomment %}-->

          <div style="height: 1px;"></div>

          <p class="mt-5 mb-3 text-muted">&copy; Copyright (주)팜플페이 </p>
        
        </form>
    </main>
    {% if messages %} {% for message in messages %}
    <div class="moveconfirm active">
        <div class="confirm-title">로그인 오류</div>
        <div class="confirm-line"></div>
        <div class="confirm-message">{{ message }}</div>
        <div class="confirm-answer-box">
            <div class="confirm-answer-omT ok">확인</div>
        </div>
    </div>
    <div class="confirm-overlay"></div>
    {% endfor %} {% endif %}

{% endif %}
</body>

<script>
    $(".ok").on("click", function () {
        $(".moveconfirm").removeClass("active");
        $(".moveconfirm").addClass("none");
        $(".confirm-overlay").fadeOut();
    });
</script>

{% endblock %}

FinFlow/templates/user/register.html
{% extends 'base.html' %}
{% block content %}

{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/user/register.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
</head>

<body class="text-center">

{% if user.is_authenticated %}
<script type="text/javascript">
  location.href="/logout";
</script>

{% else %}
    <main class="form-signin">
            <form method="post" action=".">
            {% csrf_token %}
            <img class="mb-4" src="{% static 'image/pample_logo_symbol.png' %}" alt="" width="72" height="72">
            <h1 class="h3 mb-3 fw-normal">회원가입</h1>

            <!-- 아이디 입력 -->
            <div class="form-floating">
                <input
                    id="floatingInput username"
                    class="form-control"
                    type="id"
                    placeholder="아이디" 
                    name="user_id"
                    maxlength='15'
                    oninput="this.value = this.value.replace(/[^A-Za-z0-9]/g, '').replace(/(\..*)\./g, '$1');"
                />
                
                <label for="floatingInput">
                    <p class="p-name">ID</p>
                    <p class="p-ex">(4~15자리의 영문, 숫자 조합)</p>
                </label>

            </div>

            <span id="id_error" class="forms_error" style="margin-top: 2px;">
                {% for error in form.user_id.errors %}
                {{ error }} 
                {% endfor %}
            </span>

            <p class="mt-1 text-muted"></p>

            <!-- 패스워드 입력 -->
            <div class="form-floating">
                <input
                    id="floatingPassword2"
                    class="form-control form-border"
                    type="password"
                    placeholder="Password"
                    name="password2"
                    maxlength='20'
                />

                <label for="floatingPassword2">
                    <p class="p-name">Password</p>
                    <p class="p-ex">(8개 이상의 문자, 숫자 조합)</p>
                </label>

            </div>

            <span id="pw2_error" class="forms_error" style="margin-top: -10px; text-align: left;">
                {% for error in form.password2.errors %}
                {{ error }}
                {% endfor %}
            </span>

            <p class="mt-1 text-muted"></p>  
            
            <!--비밀번호확인-->
            <div class="form-floating">
                <input
                    id="floatingPassword1"
                    class="form-control form-border"
                    type="password"
                    placeholder="Password"
                    name="password1"
                    maxlength='20'
                />

                <label for="floatingPassword1">
                    Password 확인
                </label>

            </div>

            <span id="pw1_error" class="forms_error" style="margin-top: -10px;">
                {% for error in form.password1.errors %}
                {{ error }}
                {% endfor %}
            </span>

            <!-- 사업자등록번호 입력 -->
            <div class="form-floating">
                <input
                    id="floatingInput usercmpbnum"
                    class="form-control"
                    type="text"
                    placeholder="사업자등록번호" 
                    name="user_biznum"
                    maxlength='10'
                    oninput="this.value = this.value.replace(/[^A-Za-z0-9]/g, '').replace(/(\..*)\./g, '$1');"
                />
                
                <label for="floatingInput usercmpbnum">
                    <p class="p-name">사업자등록번호</p>
                    <p class="p-ex">하이픈(-)을 제외한 숫자</p>
                </label>

            </div>
            <p class="mt-1 text-muted"></p> 

            <!--휴대폰번호-->
            <div class="form-floating">
                <input
                    id="id_hp floatingHP"
                    class="form-control form-border-hp"
                    type="text"
                    placeholder="휴대폰번호"
                    name="hp"
                    maxlength='11'
                    oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');"
                />

                <label for="floatingHP">
                    <p class="p-name">H.P</p>
                    <p class="p-ex">(하이픈(-)을 제외한 숫자로 입력)</p>
                </label>

                <button class="w-20 btn btn-lg btn-primary btn-color auth-btn"
                        type="submit"
                        formaction="../api/v1/auth-message"
                        formtarget="blankifr"
                        onclick="btnActive();">
                        인증<br>요청
                </button>

            </div>

            <span id="hp_error" class="forms_error" style="margin-top: 2px;">
                {% if errors.hp %}
                {{ errors.hp }}
                {% endif %}
            </span>

            <p class="mt-1 text-muted"></p>

            <div class="">
                <input
                    id="id_auth"
                    class="form-control auth-form"
                    type="text"
                    name="auth"
                    placeholder="인증번호 입력"
                    maxlength='6'
                    disabled
                    oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');"
                />

                <div id="timerDisplay" class="timerpos">
                    5:00
                </div>

            </div>

            <span class="forms_error" style="margin-top:2px;">
                {% if errors.auth %}
                {{ errors.auth}}
                {% endif %}
            </span>

            <p class="mt-1 text-muted"></p>

            <button class="w-100 btn btn-lg btn-primary btn-color" type="submit">
                회원가입
            </button>  
        
        </form>

        <a class="before"href="/">
            이전 페이지로
        </a>

{% endif %}

</body>

<iframe name='blankifr' style='display:none;'></iframe>
<script>
	$(document).ready(function(){
        document.getElementById("hp_error").innerHTML=""
        });
</script>
<script src="{% static 'js/user/register.js' %}"></script>

{% endblock %}